import { cn } from "@/lib/utils";
import { Providers } from "@/providers/providers";
import type { Metadata } from "next";
import { Carlito } from "next/font/google";
import "./globals.css";

const carlito = Carlito({ subsets: ["cyrillic"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-[--primary-light-gray]", carlito.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
